version: '3.8'

networks:
  my_network:
    driver: bridge

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - my_network

  frontend:
    build:
      context: ./fleet-management-frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - my_network

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - my_network