"""empty message

Revision ID: e2db15c5b429
Revises: 
Create Date: 2025-04-04 13:53:50.141020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2db15c5b429'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boyarin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('passphrase', sa.String(), nullable=False),
    sa.Column('son_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['son_id'], ['boyarin.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('letter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['boyarin.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['boyarin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('letter')
    op.drop_table('boyarin')
    # ### end Alembic commands ###
